### ISSUE TITLE
CreateServerAsync should not search for serverType

### ISSUE THREAD

**Issue by mohitsuman** [redhat-developer/rsp-client#11]
The type should be added as a parameter to the function. Currently it just takes location and name as parameter.

**Comment by jrichter1** [comment]
Wouldn't using a ServerBean object instead be faster? You get it directly from findServerBeans for a location...  and it's already implemented, you can just use it instead of the location :)

But if necessary, it can be added - as a string then?

**Comment by adietish** [comment]
This issue is outdated. VSCode is now using ```#findServerBeans```. Closing as OUTDATED
