### ISSUE TITLE
Publishing rsp-client on npm package with redhat account on npm

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/rsp-client#31]

**Comment by mohitsuman** [comment]
What is redhat account in npm registry. I guess we can add the package in registry and add collaborators to it.
Before adding a new one, we need to DEPRECATE the ssp-client package from npm registry.

**Comment by mohitsuman** [comment]
The module is published as ```rsp-client``` on npm registry.
https://www.npmjs.com/package/rsp-client. The old ```ssp-client``` is deprecated.
