### ISSUE TITLE
allow clients to remove listeners of 'serverProcessOutputAppended' events

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-client#84]
currently consumers can only add listeners for the event 'serverProcessOutputAppended' via 
```Incoming#onServerProcessOutputAppended```
Consumers should also be able to remove those listeners.
```Incoming.ts``` is generated code, we should therefore change the generated code in rsp-server to to allow this.

**Comment by adietish** [comment]
fixed by https://github.com/redhat-developer/rsp-server/issues/373

**Comment by jrichter1** [comment]
https://github.com/redhat-developer/rsp-client/blob/master/src/client.ts#L134 ?

**Comment by adietish** [comment]
@jrichter1 good pointer for the method ```#removeListener```, thx. 
But even though it seems possible (which I didnt know), that doesn't make a great API. As a dev I need to know the name of the event that's used when I add a process outpout listener. All I know without reading the client code is that there's a ```client.onProcessOutputAppended```, I dont know what event name this is operating on. I thus prefer to have a remove-method that mirrors the add-method.
* onProcessOutputAppended -> removeOnProcessOutputAppended(listener)
* etc.

**Comment by jrichter1** [comment]
It's not perfect, alright. Back then I had no desire to write 2 additional methods (removeListener, removeAllListeners) for every event available, so I just named the events as the methods without the 'on' part. If you intend to generate all this code, it's probably safe to remove the original methods.

**Comment by adietish** [comment]
@jrichter1 ok, great. Works for me. Alternatively we could also have a single method for adding and removing listeners (no named addXXX/removeXXX) and then have public constants for the event types. I just care for consistency and easy API discovery.

**Comment by adietish** [comment]
this was fixed with the following PRs:
* https://github.com/redhat-developer/rsp-server/issues/373 (generated individual add-/remove-listener methods)
* https://github.com/redhat-developer/rsp-client/pull/85 (removed the generic listener add-/remove-method) 
* https://github.com/redhat-developer/rsp-client/pull/87 (bumped rsp-client 0.16.0)

rsp-client 0.16.0 was then published to npm.
