### ISSUE TITLE
add new attribute runMode to ServerState

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/rsp-client#86]
added from rsp-server https://github.com/redhat-developer/rsp-server/pull/382

**Comment by adietish** [comment]
this was implemented in commit https://github.com/redhat-developer/rsp-client/pull/89/commits/bbf0d09e8fdfb958c69ffac0e51b4cb1fa9e2d03 aka merged in with PR https://github.com/redhat-developer/rsp-client/pull/89
Closing as DONE
