### ISSUE TITLE
setup strategy to create "snapshot" releases

### ISSUE THREAD

**Issue by adietish** [redhat-developer/rsp-client#91]
according to https://stackoverflow.com/questions/36575821/npm-install-to-get-dependency-with-tag-version npm is not able to handle -SNAPSHOT versioning like maven does. You therefore need to upversion whenever you want to publish a new version. 
There's still a valid strategy though where we would upversion rsp-client using "-SNAPSHOT.X" where X is a unique numeric identifier. In vscode we would then depend on "-SNAPSHOT" (no numeric identifier) and npm would fetch the latest "-SNAPSHOT.X" there is. There's a drawback though: once the next non-snapshot version gets available, the dependency to rsp-client needs to be updated in vscode-adapters. 

ex. rsp-client 1.9.1-SNAPSHOT.1 would not satisfy a dependency in vscode-adapter specifying 1.9.0-SNAPSHOT (1.9.1 would be satisfying it though). When bumping the version in rsp-client, we'd need to bump the dependency in vscode-adapter.
For more details look at the answer here: https://stackoverflow.com/a/34978416/231357 or here: https://stackoverflow.com/questions/28636506/npm-outdated-does-not-respect-caret-notation-of-package-json

There are several scripts that would automatically append "-SNAPSHOT.X" and bump the "X" to your version in package.json:
* https://www.npmjs.com/package/npm-snapshot
* https://www.npmjs.com/package/snapshot-publish
* https://www.npmjs.com/package/npm-auto-snapshot

@jrichter1 dare to comment please?

**Comment by jrichter1** [comment]
What exactly is this supposed to achieve anyway?

**Comment by adietish** [comment]
@jrichter1 fair point: not to have to increase the proper version (but the prerelease-tag) while publishing new builds of the client. Ideally server, client, vscode all match in version.
At some point in the future I'd see a fresh server build trigger a new client build which then results in a new vscode-build.

**Comment by jrichter1** [comment]
Sounds like the easiest solution for this is not to use snapshots at all :stuck_out_tongue_winking_eye:

**Comment by adietish** [comment]
@adietish explain? 0.16.242 in client while server is still at 0.16.0-SNAPSHOT sounds like a great option to you?

**Comment by jrichter1** [comment]
client being 0.16.0 while server is 0.16.0

**Comment by adietish** [comment]
@jrichter1 server is maven based which knows the concept of SNAPSHOT. There is no NON-SNAPSHOT version in server. And this makes perfect sense: a SNAPSHOT is considered a nightly build where the API can change any time. It prevents you from having to bump the version any time you change something a publish a new build. 
So if there's a new server SNAPSHOT, you'd publish the new client to 0.16.896 etc?

**Comment by jrichter1** [comment]
I'd get rid of the SNAPSHOT, just bump the damn server as well

**Comment by adietish** [comment]
-1, you definitely want to be able to publish nightly builds without having to bump the version. If it's only with a timestamp, fair enough.

**Comment by jrichter1** [comment]
So you'd rather hack around the whole npm workflow than have a maven package not do snapshots.

**Comment by adietish** [comment]
if you want nightly "unstable" builds, then this is the best approach imho.

**Comment by jrichter1** [comment]
If you simply abandon using version qualifiers, the only thing you lose is the ability to publish to snapshot maven repos. Which doesn't look like such a problem, because nobody is consuming them anyway.

The only way rsp is consumed is here:
https://github.com/redhat-developer/vscode-adapters/blob/master/build/package.js#L6

And these snapshots are generated regardless of the current version.

**Comment by jrichter1** [comment]
The other thing to mention here is that npm packages don't need to be loaded from npm.
If you wish to make snapshots of the client, you can just upload a tarball and consume it from a URL. Or load it directly from github, prefferably from a branch.

**Comment by jrichter1** [comment]
snapshots available at https://download.jboss.org/jbosstools/adapters/snapshots/vscode-middleware-tools/rsp-client/
